### ISSUE TITLE
Use gulp-rename instead of making a new module

### ISSUE THREAD

**Issue by phated** [marius-t/gulp-jade2#1]
This module is unnecessary because gulp-rename lets you put a different file extension on your output file.

**Comment by marius-t** [comment]
Thank you for the comment, I did not knew about gulp-rename, I will give it a shoot, but my problem is that I have a lot of bower_components that have .jade templates and those need to get into Angular's $templateCache and I had some issue with that (because gulp-jade - will rename the templates into .html or .js) and in the apps the templates are all *.jade.
Thanks again
